### ISSUE TITLE
The input does not focus, on click of new message button in  top right corner

### ISSUE THREAD

**Issue by anish-work** [GooeyAI/gooey-web-widget#1]
<img width="214" alt="Screenshot 2024-06-06 at 6 39 22 PM" src="https://github.com/GooeyAI/gooey-web-widget/assets/65861855/2acdbee6-fcd9-4b01-9d83-7cbd56b6dcc7">

On Click of new message (pencil edit icon) button in top right corner, all this should happen:
- The message input should get focused (cursor should blink and in mobile devices keyboard should open).
- All messages should be cleared from state.
- API call should be cancelled if any in progress.

The first point is not happening, please fix this!

**Comment by robGardiner01** [comment]
I've managed to fix the issue but its not letting me push the branch. The instructions aren't very clear about how I go about this

**Comment by robGardiner01** [comment]
I've made a PR to fix this issue if you'd like to check it out?

**Comment by anish-work** [comment]
> I've made a PR to fix this issue if you'd like to check it out?

Sure I will give it a try

**Comment by robGardiner01** [comment]
Any update on the PR?

**Comment by anish-work** [comment]
![Screenshot 2024-08-07 at 12 58 48 AM](https://github.com/user-attachments/assets/58268170-00b1-4c82-9657-4b3dab8a21b5)
It focus on the first button instead!

@robGardiner01 I tested your PR, it looks like it doesn't work when the widget is being injected on separate html. Try doing this: 
- Create a test-site/ folder
- make .html file and try to inject the script pointing to the local build server
- Test there

**Comment by robGardiner01** [comment]
Sorry, it was previously selecting the first element instead of getting the element from its name. I'll go fix that
